### ISSUE TITLE
[10.5.0] Download fails after pressing Download button on palemoon forum

### ISSUE THREAD

**Issue by SXZ1** [mozilla-services/screenshots#3038]
Hello!
STR:
Nightly 14-06-17, create new profile, launch it
Go to https://forum.palemoon.org/viewtopic.php?f=46&p=115732
Click on screenshot icon
Hover the mouse near the red dot and press left mouse button in order to select part of the page shown on the screenshot
Press Download button

ER: Screenshot is saved on disk
AR: Download fails
![image](https://user-images.githubusercontent.com/26294581/27147703-6bcb2ab4-5146-11e7-9b84-c72c3521f2cb.png)

**Comment by SXZ1** [comment]
Screenshot of the browser console:
![image](https://user-images.githubusercontent.com/26294581/27148883-88867f56-514a-11e7-8437-c32b4e44656d.png)

**Comment by 6a68** [comment]
@SXZ1 Hi, this seems vaguely like https://bugzil.la/1298362. I wonder if it's a Nightly bug.

Do you have any addons installed? What are your history settings? Are you able to download other files? Does the problem go away after a restart?

**Comment by 6a68** [comment]
@SXZ1 Also, what OS are you on?

**Comment by SXZ1** [comment]
Hello!
I created a new profile before trying to reproduce this bug so I don't have any addons installed, history settings are default, I can download screenshots from other sites, I can download other files, problem doesn't go away after restart. Win8.1 x64 with latest updates/security updates.

**Comment by SXZ1** [comment]
Screenshot of history settings in the new profile that I used to reproduce the bug:
![image](https://user-images.githubusercontent.com/26294581/27155387-781227bc-5161-11e7-8704-0a1e43e66c8e.png)

**Comment by SXZ1** [comment]
I also couldn't reproduce the bug 1298362 using str from comment 0:
https://bugzilla.mozilla.org/show_bug.cgi?id=1298362#c0
I can download beta without failure code 0x80070057 in the console. Here is the screenshot of the browser console after I downloaded beta installer (notice I enabled Server tab):
![image](https://user-images.githubusercontent.com/26294581/27156895-d0923e58-5167-11e7-9a5f-34a05f9310f2.png)

**Comment by SXZ1** [comment]
Also, Palemoon forum is not the only web page where I can reproduce this bug: download also fails on reddit. Take a look at this comment:
https://github.com/mozilla-services/screenshots/issues/2895#issuecomment-305204315

**Comment by SXZ1** [comment]
One more page where download fails:
http://forums.watchuseek.com/f2/cheapest-new-watch-valjoux-7750-movement-90398-2.html#post41718482

**Comment by ianb** [comment]
I don't this is related to the page that's being shot (at least I don't think?), but it's probably related to #2981 – which is a download error that we're seeing regularly in our error reporting, but haven't figured out how to reproduce.

**Comment by 6a68** [comment]
Looking a little more closely at the [browser console screenshot](https://github.com/mozilla-services/screenshots/issues/3038#issuecomment-308522707) above, it looks like "Win error 123" is due to illegal characters in the filename.

I wonder if #3084 (better sanitizing filenames) might have fixed the underlying bug here

**Comment by SXZ1** [comment]
Nightly 16-07-17, Screenshots 10.5.0 with #3084 landed, I can still reproduce the bug from the first post, same STR: Screenshot of the browser console:
![image](https://user-images.githubusercontent.com/26294581/28267029-d7f5c2d4-6b00-11e7-9df2-4e1ed835bdbd.png)

**Comment by ianb** [comment]
I believe this has been fixed by improving our filename sanitization (in #3084)

**Comment by SXZ1** [comment]
No, it was not, I can still reproduce this bug using STR from the 1st post. Nightly 01-08-17, SC10.9.0
