### ISSUE TITLE
[Annotations] The highlighter looks wrongly jagged instead of smooth when its direction is changed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#3934]
[Affected versions]:
- Nightly 59.0a1
- Screenshots 27.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 27.0.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile.  

[Steps to reproduce]:
1. Open latest Nightly build with the profile from prerequisites and navigate to any website.
2. Save a selection on the page and click the "Edit this image" button.
3. Select the "Highlighter" tool.
4. Draw a circle on the page and observe the highlighter.

[Expected result]:
- The highlighter is drawn smooth. 

[Actual result]:
- The highlighter looks jagged.

[Notes]:
- Here is a screen recording with the issue:
![jagged highlighter](https://user-images.githubusercontent.com/19226534/34570144-97d9e8b6-f173-11e7-94dd-0a6310ea3e21.gif)

**Comment by chenba** [comment]
This was fixed in #4045.

(@niharikak101 when you add a fix to an existing PR, could you also update the PR description so the issue is auto closed on merge?  Thanks)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible on Mac OS . The highlighter looks jagged while drawing slowly and moving its direction. 
Here is a screen recording with the issue: https://goo.gl/mBf8FH

On Windows and Linux the issue is not reproducible but, you can observe that the highlighter pointer is a square and while changing the drawing direction the square wrongly rotates.
Here is a screen recording with this behavior: https://goo.gl/Z1CEVb
