### ISSUE TITLE
Screenshot crop is misaligned on specific page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#4018]
Copied from [Bug 1432755](https://bugzilla.mozilla.org/show_bug.cgi?id=1432755)

User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
Build ID: 20180118215408

Steps to reproduce:

* Deploy [the page](https://bugzilla.mozilla.org/attachment.cgi?id=8945048) attached on a local server (apache, or other, does not matter) (it fails with other pages on localhost too, but not directory listings, so I provided a page with which it occurs)
* Open the screenshots tool in the awesome bar
* With the mouse (not the "Capture the whole page button), try to capture from the left of the window to the right

Actual results:

You can't reach the right side.
If you submit the screenshot like this, it appears like the whole crop zone was translated on the horizontal axis.

Look at this screenshot (made with another tool): https://framapic.org/2fkK8KYJvtgA/EdyujaPoB7tH.png

The black zone does not reach the right side.

Expected results:

I should be able to capture the whole width.

**Comment by nicofrand** [comment]
I tried reducing it to a small case but it seems to appear only on localhost and even when removing most of the DOM nodes the issue persisted.

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this issue using the provided page on latest Firefox 58.0 release on Windows 7 x64.  But, the issue is not reproducible on latest Nightly 60.0a1 build.

I think that this issue is similar with #3907 which was fixed in the latest Screenshots versions.
@nicofrand can you retest this on latest Nightly 60.0a1 build and confirm that the issue is fixed?

**Comment by nicofrand** [comment]
Hi !

It does seem to be a duplicate indeed. However the nightly did not fix the issue of npr.org:

![bug-firefox](https://user-images.githubusercontent.com/3419050/35445285-746d8f82-02b1-11e8-91eb-45d98fe8b778.png)

It did not fix it with my page neither:

![bug-firefox](https://user-images.githubusercontent.com/3419050/35445451-f0333f5e-02b1-11e8-830f-aae41de252cc.png)

PS : feel free to reopen the other issue and close this one (and copy my comment/screenshot maybe)

**Comment by SoftVision-CosminMuntean** [comment]
@nicofrand I'm sorry for sending you on a wild goose chase! It seems that the fix didn't land in Nightly yet and I didn't notice that I had tested this scenario using Screenshots 28.0.0 dev version. However, the issue is fixed and will land in the next release.
You can also check this by installing the Screenshots dev version from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html).

**Comment by nicofrand** [comment]
That's ok, glad it's fixed ! Well done to everyone involved.

I confirm this is fixed for both npr.org and my case, you can close this issue, thanks !
