### ISSUE TITLE
[Annotations] Annotation tools are broken on smaller screens or if the page zoom level was changed before editing

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4453]
[Notes]:
- On smaller screen (eg Mac Book Pro 13 inch) the issue is reproducible without changing the zoom level.

[Affected versions]:
- Nightly 62.0a1
- Screenshots 32.1.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 32.1.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Change the the zoom level of the page (eg: 120%).
3. Click the "Edit this image" button.
4. Using the "Pen" tool draw a line on the page and observe the behavior.
5. Using the "Highlighter" tool draw a line on the page and observe the behavior.
6. Click the "Clear" button and observe the behavior.

[Expected result]:
Step 4: The line is correctly drawn on the image according to the mouse position.
Step 5: The line is correctly drawn on the image according to the mouse position.
Step 6: The changes are reverted.

[Actual results]:
Step 4: The line is drawn in a different position.
Step 5: The part of the image where drawing was performed is duplicated and displayed in a different position.
Step 6: The changes are reverted but the image is wrongly zoomed in.

[Additional Notes]:
- On smaller screens (eg: Mac Book Pro) the size of the drawing is also displayed smaller. 
- Here is a screen recording with the issue:
![annotation tools](https://user-images.githubusercontent.com/19226534/40059182-1185809a-585c-11e8-8cd2-871de12eb000.gif)

**Comment by chenba** [comment]
PR #4465 should fixes this as well.  Please verify once that's merged.

**Comment by chenba** [comment]
Fixed in #4465

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the latest Screenshots (32.1.0) dev version but the issue is still reproducible for the following scenarios:

**- For the "Clear" button. Here are the STR:**
1. Navigate to the saved shot link.
2. Change the the zoom level of the page (eg: 120%).
3. Click the "Edit this image" button.
4. Click the "Clear" button and observe the behavior.

[Actual Results]:
- The changes are reverted but the image is wrongly zoomed in.
- Also, the "Pen" tool wrongly draws on the image after the "Clear" button was pressed,
- Here is a screen recording with the described scenario:
![clear](https://user-images.githubusercontent.com/19226534/40476528-f0dccf40-5f4c-11e8-9143-c52ba524ce13.gif)


**- If the image was croped, the pen tool is wrongly drawn. Here are the STR**
1. Navigate to the saved shot link.
2. Change the the zoom level of the page (eg: 120%).
3. Click the "Edit this image" button.
4. Click the "Crop" button and crop the image.
5. Click the "Pen" tool and draw a line on the image.
6. Observe the behavior.

[Actual Results]:
- The line is drawn in a different position. However, the Highlighter tool works as expected.
- Here is a screen recording with the described scenario:
![pen tool after crop](https://user-images.githubusercontent.com/19226534/40476499-d9b3508c-5f4c-11e8-9b5b-3870fdc12fec.gif)


Both scenarios are reproducible on smaller screens (eg Mac Book Pro) without changing the zoom level.

**Comment by SoftVision-CosminMuntean** [comment]
@chenba it seems that the issue is not reproducible for "Save Full pages", but is reproducible for "Save visible" pages and selections.

Also, is only for me or "Save Full pages" it takes too long until is saved? And sometimes I get a "Out of order" error and the shot is not saved.

**Comment by chenba** [comment]
This will be fixed when PR #4482 is merged.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on latest Screenshots (33.0.0) dev version and it seems that it is partially fixed. The issue is still reproducible if the image is cropped:
- The tool that was selected before the image was cut, wrongly draws in another position. But, if the tool is changed the issue is no longer be reproducible.
- The "Clear" functionality is also broken if the image was cropped, but this behavior is logged in issue #4509.

The issue is reproducible on smaller screen, but it is also reproducible on larger screens if the page zoom level is changed.
Here is a screen recording with the issue:
![cropped image](https://user-images.githubusercontent.com/19226534/40781748-b33f4a66-64e5-11e8-9431-1a545b1cbf81.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Screenshots (33.0.0) dev version and it is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux 4.12 x64.
